// Mock Notifications Data for Smart Civic Issue & Complaint Management System
// Admin Notifications Module

export const initialNotifications = [
  {
    id: "NOT-1001",
    type: "complaint",
    title: "High-priority complaint reported",
    message: "A new high-priority pothole complaint has been submitted in Thatipur.",
    description: "Citizen reported severe crater causing vehicle slowdown and hazard on Thatipur Main Road. Requires municipal inspection.",
    timestamp: "2026-09-06T22:30:00Z",
    timeAgo: "15 minutes ago",
    read: false,
    priority: "High",
    relatedEntity: "complaint",
    relatedId: "CMP-1024",
    area: "Thatipur",
    sender: "Citizen Mobile Portal",
    category: "Complaint Updates"
  },
  {
    id: "NOT-1002",
    type: "department",
    title: "Department workload threshold exceeded",
    message: "Road Maintenance active complaints exceeded 40 tickets.",
    description: "Road Maintenance has reached 42 active tickets. Additional field crews may need to be dispatched to prevent SLA breach.",
    timestamp: "2026-09-06T21:45:00Z",
    timeAgo: "1 hour ago",
    read: false,
    priority: "High",
    relatedEntity: "department",
    relatedId: "DEPT-001",
    area: "Municipal HQ",
    sender: "Workload Monitor",
    category: "Department Updates"
  },
  {
    id: "NOT-1003",
    type: "complaint",
    title: "Hazardous electric post reported",
    message: "Fallen utility post leaning at 45-degree angle in Gola Ka Mandir.",
    description: "Electrical pole threatening residential perimeter wall after squall winds. Assigned to Electrical Department.",
    timestamp: "2026-09-06T20:10:00Z",
    timeAgo: "2 hours ago",
    read: false,
    priority: "High",
    relatedEntity: "complaint",
    relatedId: "CMP-1038",
    area: "Gola Ka Mandir",
    sender: "Smart Civic System",
    category: "Complaint Updates"
  },
  {
    id: "NOT-1004",
    type: "user",
    title: "New department staff registered",
    message: "Karan Mehra registered as Traffic Management Department Head.",
    description: "Administrator approved staff account for Karan Mehra with official email karan.mehra@civis.gov.in.",
    timestamp: "2026-09-06T18:00:00Z",
    timeAgo: "4 hours ago",
    read: true,
    priority: "Medium",
    relatedEntity: "user",
    relatedId: "USR-1011",
    area: "City Centre",
    sender: "User Directory Service",
    category: "User Updates"
  },
  {
    id: "NOT-1005",
    type: "complaint",
    title: "Sewage leakage complaint escalated",
    message: "Underground drainage chamber overflowing in Hazira.",
    description: "Complaint CMP-1042 escalated due to contamination risk near municipal park entrance.",
    timestamp: "2026-09-06T16:20:00Z",
    timeAgo: "6 hours ago",
    read: false,
    priority: "High",
    relatedEntity: "complaint",
    relatedId: "CMP-1042",
    area: "Hazira",
    sender: "SLA Escalation Engine",
    category: "Complaint Updates"
  },
  {
    id: "NOT-1006",
    type: "department",
    title: "Sanitation completed waste clearance",
    message: "Community dumpster cleared at City Centre Sector 7.",
    description: "Sanitation Department dispatched compactor vehicle and completed clearance for ticket CMP-1025.",
    timestamp: "2026-09-06T14:30:00Z",
    timeAgo: "8 hours ago",
    read: true,
    priority: "Low",
    relatedEntity: "department",
    relatedId: "DEPT-002",
    area: "City Centre",
    sender: "Sanitation Dispatch",
    category: "Department Updates"
  },
  {
    id: "NOT-1007",
    type: "system",
    title: "GIS Geotagging sync completed",
    message: "Gwalior municipal sector coordinates refreshed.",
    description: "Synchronized 18 GIS map pins with spatial boundaries in the Complaint Map module.",
    timestamp: "2026-09-06T11:00:00Z",
    timeAgo: "11 hours ago",
    read: true,
    priority: "Low",
    relatedEntity: "map",
    relatedId: "MAP-ZONE-1",
    area: "GIS Zone",
    sender: "GIS Core Service",
    category: "System Alerts"
  },
  {
    id: "NOT-1008",
    type: "user",
    title: "Citizen submitted 5-star resolution feedback",
    message: "Sunita Rao confirmed resolution for drinking water issue.",
    description: "Citizen expressed satisfaction with rapid pipeline repair completed by Water Supply department in Morar.",
    timestamp: "2026-09-06T09:15:00Z",
    timeAgo: "13 hours ago",
    read: false,
    priority: "Medium",
    relatedEntity: "user",
    relatedId: "USR-1008",
    area: "Morar",
    sender: "Feedback Portal",
    category: "User Updates"
  },
  {
    id: "NOT-1009",
    type: "complaint",
    title: "Drinking water pipeline repair assigned",
    message: "Subterranean supply pipe fracture assigned to Water Supply.",
    description: "Jal Bhawan team dispatched to Morar market entrance to isolate fractured valve and prevent water loss.",
    timestamp: "2026-09-05T19:40:00Z",
    timeAgo: "Yesterday, 7:40 PM",
    read: true,
    priority: "High",
    relatedEntity: "complaint",
    relatedId: "CMP-1027",
    area: "Morar",
    sender: "Smart Civic System",
    category: "Complaint Updates"
  },
  {
    id: "NOT-1010",
    type: "department",
    title: "Drainage team resolved sewer blockage",
    message: "Manhole cover replaced at Gola Ka Mandir.",
    description: "Heavy reinforced concrete cover installed and tested for pedestrian safety.",
    timestamp: "2026-09-05T17:15:00Z",
    timeAgo: "Yesterday, 5:15 PM",
    read: true,
    priority: "Medium",
    relatedEntity: "department",
    relatedId: "DEPT-005",
    area: "Gola Ka Mandir",
    sender: "Drainage Department",
    category: "Department Updates"
  },
  {
    id: "NOT-1011",
    type: "user",
    title: "Citizen account flagged for suspicious activity",
    message: "Ritu Saxena account suspended following automated policy review.",
    description: "Account was flagged for submitting repeated automated reports from conflicting coordinates in Lashkar.",
    timestamp: "2026-09-05T15:00:00Z",
    timeAgo: "Yesterday, 3:00 PM",
    read: false,
    priority: "High",
    relatedEntity: "user",
    relatedId: "USR-1014",
    area: "Lashkar",
    sender: "Security Audit Engine",
    category: "User Updates"
  },
  {
    id: "NOT-1012",
    type: "system",
    title: "Daily automated database snapshot succeeded",
    message: "System state backup archived successfully.",
    description: "Snapshot of active complaints, users, and department rosters backed up to local server storage.",
    timestamp: "2026-09-05T12:00:00Z",
    timeAgo: "Yesterday, 12:00 PM",
    read: true,
    priority: "Low",
    relatedEntity: "system",
    relatedId: "SYS-BAK-20260905",
    area: "Data Center",
    sender: "System Backup Agent",
    category: "System Alerts"
  },
  {
    id: "NOT-1013",
    type: "complaint",
    title: "Broken traffic signal reported",
    message: "Simultaneous red/green light signal error at Phool Bagh.",
    description: "Traffic junction controller glitch causing vehicle gridlock. Assigned to Traffic Management.",
    timestamp: "2026-09-05T10:20:00Z",
    timeAgo: "Yesterday, 10:20 AM",
    read: true,
    priority: "High",
    relatedEntity: "complaint",
    relatedId: "CMP-1029",
    area: "Phool Bagh",
    sender: "Traffic Command",
    category: "Complaint Updates"
  },
  {
    id: "NOT-1014",
    type: "department",
    title: "Traffic signaling controller rebooted",
    message: "Signals synchronized at Phool Bagh junction.",
    description: "Traffic warden team confirmed normal light cycles restored and traffic flow cleared.",
    timestamp: "2026-09-05T08:30:00Z",
    timeAgo: "Yesterday, 8:30 AM",
    read: true,
    priority: "Medium",
    relatedEntity: "department",
    relatedId: "DEPT-006",
    area: "Phool Bagh",
    sender: "Traffic Department",
    category: "Department Updates"
  },
  {
    id: "NOT-1015",
    type: "complaint",
    title: "Road asphalt peeled away",
    message: "Top tar surface washed out along University Road.",
    description: "Gravel stones causing two-wheeler slippage near university entrance. Status marked Pending.",
    timestamp: "2026-09-04T18:00:00Z",
    timeAgo: "Sep 04, 2026",
    read: true,
    priority: "Medium",
    relatedEntity: "complaint",
    relatedId: "CMP-1040",
    area: "University Road",
    sender: "Citizen Web Portal",
    category: "Complaint Updates"
  },
  {
    id: "NOT-1016",
    type: "user",
    title: "15 new citizens registered today",
    message: "Milestone reached for municipal citizen portal onboarding.",
    description: "Citizen verification rate reached 98% across Thatipur and City Centre wards.",
    timestamp: "2026-09-04T14:15:00Z",
    timeAgo: "Sep 04, 2026",
    read: false,
    priority: "Low",
    relatedEntity: "user",
    relatedId: "USR-SUMMARY",
    area: "All Wards",
    sender: "Registration Service",
    category: "User Updates"
  },
  {
    id: "NOT-1017",
    type: "system",
    title: "API rate limit safeguard triggered",
    message: "Transient burst in spatial map geocoding queries detected.",
    description: "Automatic cache protection activated for 10 minutes to prevent API throttle.",
    timestamp: "2026-09-04T11:45:00Z",
    timeAgo: "Sep 04, 2026",
    read: true,
    priority: "Medium",
    relatedEntity: "system",
    relatedId: "SYS-RATE-04",
    area: "API Gateway",
    sender: "Security Gateway",
    category: "System Alerts"
  },
  {
    id: "NOT-1018",
    type: "complaint",
    title: "High-voltage wire sparking incident",
    message: "Lashkar market transformer wire contacting tree branch.",
    description: "Electrical Department dispatched emergency response truck to prune branches and reinsulate conductor.",
    timestamp: "2026-09-04T09:30:00Z",
    timeAgo: "Sep 04, 2026",
    read: true,
    priority: "High",
    relatedEntity: "complaint",
    relatedId: "CMP-1026",
    area: "Lashkar",
    sender: "Smart Civic System",
    category: "Complaint Updates"
  },
  {
    id: "NOT-1019",
    type: "department",
    title: "Water Supply pressure test completed",
    message: "Main feeder reservoir line at Morar verified intact.",
    description: "Average tap water pressure stabilized across 12,000 consumer connections in Zone 4.",
    timestamp: "2026-09-03T16:20:00Z",
    timeAgo: "Sep 03, 2026",
    read: true,
    priority: "Low",
    relatedEntity: "department",
    relatedId: "DEPT-004",
    area: "Morar",
    sender: "Water Supply Department",
    category: "Department Updates"
  },
  {
    id: "NOT-1020",
    type: "complaint",
    title: "Garbage container clearance delayed",
    message: "Sanitation vehicle breakdown in City Centre.",
    description: "Backup compactor truck deployed to complete the evening round with a 45-minute delay.",
    timestamp: "2026-09-03T14:00:00Z",
    timeAgo: "Sep 03, 2026",
    read: true,
    priority: "Medium",
    relatedEntity: "complaint",
    relatedId: "CMP-1025",
    area: "City Centre",
    sender: "Sanitation Dispatch",
    category: "Complaint Updates"
  },
  {
    id: "NOT-1021",
    type: "system",
    title: "Scheduled maintenance notification",
    message: "Server maintenance window planned for upcoming Sunday midnight.",
    description: "Infrastructure upgrades will apply performance indexing patches. Downtime estimated at 15 minutes.",
    timestamp: "2026-09-02T16:00:00Z",
    timeAgo: "Sep 02, 2026",
    read: false,
    priority: "Medium",
    relatedEntity: "system",
    relatedId: "SYS-MAINT-01",
    area: "System Core",
    sender: "Infrastructure Ops",
    category: "System Alerts"
  },
  {
    id: "NOT-1022",
    type: "user",
    title: "New administrator permissions assigned",
    message: "Kavita Chouhan granted elevated municipal admin privileges.",
    description: "Authorized for system configuration, department reassignment, and policy escalations.",
    timestamp: "2026-09-02T11:15:00Z",
    timeAgo: "Sep 02, 2026",
    read: true,
    priority: "High",
    relatedEntity: "user",
    relatedId: "USR-1016",
    area: "City Centre",
    sender: "Chief Administrator",
    category: "User Updates"
  },
  {
    id: "NOT-1023",
    type: "complaint",
    title: "Road divider damage in University Road",
    message: "Cement divider curbing dislodged onto driving lane.",
    description: "Road Maintenance placed cautionary markers and scheduled cement masonry work for CMP-1030.",
    timestamp: "2026-08-30T10:00:00Z",
    timeAgo: "Aug 30, 2026",
    read: true,
    priority: "Medium",
    relatedEntity: "complaint",
    relatedId: "CMP-1030",
    area: "University Road",
    sender: "Smart Civic System",
    category: "Complaint Updates"
  },
  {
    id: "NOT-1024",
    type: "department",
    title: "Monthly civic resolution rate target achieved",
    message: "Overall municipal resolution rate reached 82% in August.",
    description: "Sanitation and Traffic Management led departmental resolution velocity with 91% and 88% respectively.",
    timestamp: "2026-08-28T18:30:00Z",
    timeAgo: "Aug 28, 2026",
    read: true,
    priority: "Low",
    relatedEntity: "department",
    relatedId: "DEPT-SUMMARY",
    area: "All Departments",
    sender: "Municipal Analytics",
    category: "Department Updates"
  },
  {
    id: "NOT-1025",
    type: "complaint",
    title: "Streetlights outage resolved in Madhav Nagar",
    message: "6 sodium lamps replaced with LED fixtures.",
    description: "Electrical crew confirmed full circuit reactivation. Ticket CMP-1031 marked Resolved.",
    timestamp: "2026-08-28T15:20:00Z",
    timeAgo: "Aug 28, 2026",
    read: true,
    priority: "Low",
    relatedEntity: "complaint",
    relatedId: "CMP-1031",
    area: "Madhav Nagar",
    sender: "Electrical Department",
    category: "Complaint Updates"
  },
  {
    id: "NOT-1026",
    type: "system",
    title: "SSL Certificate auto-renewal successful",
    message: "Security certificate renewed for *.civis.gov.in domain.",
    description: "Transport Layer Security (TLS 1.3) validity extended for 365 days.",
    timestamp: "2026-08-25T03:00:00Z",
    timeAgo: "Aug 25, 2026",
    read: true,
    priority: "Low",
    relatedEntity: "system",
    relatedId: "SYS-SSL-2026",
    area: "Security Core",
    sender: "Cert Authority Agent",
    category: "System Alerts"
  }
];

// Helper to determine Date Grouping
export const getDateGroup = (timestamp) => {
  const date = new Date(timestamp);
  const now = new Date('2026-09-06T23:59:59Z');
  const oneDay = 24 * 60 * 60 * 1000;

  const diffDays = Math.floor((now.getTime() - date.getTime()) / oneDay);

  if (diffDays === 0) return 'TODAY';
  if (diffDays === 1) return 'YESTERDAY';
  return 'EARLIER';
};
